name: aura_app
description: A Flutter app with Digital Bioluminescence theme
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.5.4
  http: ^1.6.0
  flutter_dotenv: ^6.0.0
  supabase_flutter: ^2.12.0
  intl: ^0.20.2
  confetti: ^0.8.0
  flutter_native_splash: ^2.3.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1" 

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/

# --- CONFIGURATION ---

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_blue.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0F172A"
  adaptive_icon_foreground: "assets/images/logo_test_padded.png"

flutter_native_splash:
  color: "#0F172A"
  image: "assets/images/logo_blue.png"
  android_12:
    color: "#0F172A"
    image: "assets/images/logo_test_padded.png"
  web: false